INSERT IGNORE INTO categories (name, slug, description, sort_order, image) VALUES
('Electronics', 'electronics', 'Gadgets, devices and tech accessories.', 1, NULL),
('Smartphones', 'smartphones', 'Mobile phones and accessories.', 2, NULL),
('Laptops & Computers', 'laptops-computers', 'Notebooks, desktops and peripherals.', 3, NULL),
('Audio', 'audio', 'Headphones, earbuds and speakers.', 4, NULL),
('Wearables', 'wearables', 'Smartwatches, fitness trackers and more.', 5, NULL),
('Fashion', 'fashion', 'Clothing, footwear and accessories.', 6, NULL),
('Men', 'men', 'Menswear and grooming.', 7, NULL),
('Women', 'women', 'Womenswear and beauty.', 8, NULL),
('Home', 'home', 'Furniture, decor and kitchenware.', 9, NULL),
('Furniture', 'furniture', 'Sofas, tables and storage.', 10, NULL),
('Kitchen', 'kitchen', 'Appliances, cookware and utensils.', 11, NULL),
('Beauty & Health', 'beauty-health', 'Skincare, supplements and wellness.', 12, NULL),
('Sports & Outdoors', 'sports-outdoors', 'Fitness, camping and outdoor gear.', 13, NULL),
('Toys & Games', 'toys-games', 'Games, puzzles and kids toys.', 14, NULL),
('Automotive', 'automotive', 'Car accessories and tools.', 15, NULL);

INSERT IGNORE INTO products (owner_id, vendor_id, name, slug, description, short_description, price, compare_at_price, currency, stock_qty, inventory_status, category_id, is_affiliate_eligible, affiliate_commission_type, affiliate_commission_value, status, featured, visibility) VALUES
(1, NULL, 'iPhone 15 Pro', 'iphone-15-pro', 'Latest Apple smartphone with titanium design.', 'Premium smartphone.', 999.00, 1099.00, 'USD', 25, 'in_stock', (SELECT id FROM categories WHERE slug='smartphones'), 1, 'percentage', 5.00, 'published', 1, 'public'),
(1, NULL, 'Samsung Galaxy S24', 'samsung-galaxy-s24', 'Flagship Android with AI features.', 'High-end Android phone.', 899.00, 999.00, 'USD', 18, 'in_stock', (SELECT id FROM categories WHERE slug='smartphones'), 1, 'percentage', 5.00, 'published', 0, 'public'),
(1, NULL, 'Pixel 8 Pro', 'pixel-8-pro', 'Google Pixel with advanced camera.', 'Best camera phone.', 799.00, 899.00, 'USD', 12, 'in_stock', (SELECT id FROM categories WHERE slug='smartphones'), 1, 'percentage', 5.00, 'published', 0, 'public'),
(1, NULL, 'MacBook Air M3', 'macbook-air-m3', 'Lightweight laptop with Apple silicon.', 'Ultra-portable laptop.', 1199.00, 1299.00, 'USD', 10, 'in_stock', (SELECT id FROM categories WHERE slug='laptops-computers'), 1, 'percentage', 6.00, 'published', 1, 'public'),
(1, NULL, 'Dell XPS 15', 'dell-xps-15', 'Powerful Windows laptop for creators.', 'Creator laptop.', 1499.00, 1699.00, 'USD', 7, 'in_stock', (SELECT id FROM categories WHERE slug='laptops-computers'), 1, 'percentage', 6.00, 'published', 0, 'public'),
(1, NULL, 'Sony WH-1000XM5', 'sony-wh-1000xm5', 'Industry leading noise cancelling headphones.', 'Wireless over-ear headphones.', 348.00, 399.00, 'USD', 40, 'in_stock', (SELECT id FROM categories WHERE slug='audio'), 1, 'percentage', 7.00, 'published', 1, 'public'),
(1, NULL, 'AirPods Pro 2', 'airpods-pro-2', 'Apple active noise cancelling earbuds.', 'Premium wireless earbuds.', 249.00, 299.00, 'USD', 60, 'in_stock', (SELECT id FROM categories WHERE slug='audio'), 1, 'percentage', 6.00, 'published', 0, 'public'),
(1, NULL, 'Bose SoundLink', 'bose-soundlink', 'Portable Bluetooth speaker.', 'Compact speaker.', 129.00, 149.00, 'USD', 30, 'in_stock', (SELECT id FROM categories WHERE slug='audio'), 1, 'percentage', 6.00, 'published', 0, 'public'),
(1, NULL, 'Apple Watch Ultra 2', 'apple-watch-ultra-2', 'Rugged smartwatch for athletes.', 'Adventure smartwatch.', 799.00, 849.00, 'USD', 15, 'in_stock', (SELECT id FROM categories WHERE slug='wearables'), 1, 'percentage', 6.00, 'published', 1, 'public'),
(1, NULL, 'Garmin Fenix 7', 'garmin-fenix-7', 'Multisport GPS smartwatch.', 'Fitness smartwatch.', 549.00, 599.00, 'USD', 20, 'in_stock', (SELECT id FROM categories WHERE slug='wearables'), 1, 'percentage', 6.00, 'published', 0, 'public'),
(1, NULL, 'Leather Jacket', 'leather-jacket', 'Classic mens leather jacket.', 'Stylish outerwear.', 199.00, 249.00, 'USD', 35, 'in_stock', (SELECT id FROM categories WHERE slug='men'), 1, 'percentage', 8.00, 'published', 0, 'public'),
(1, NULL, 'Running Shoes', 'running-shoes', 'Lightweight performance running shoes.', 'Mens running shoes.', 89.00, 120.00, 'USD', 50, 'in_stock', (SELECT id FROM categories WHERE slug='men'), 1, 'percentage', 7.00, 'published', 0, 'public'),
(1, NULL, 'Summer Dress', 'summer-dress', 'Light floral summer dress.', 'Womens dress.', 59.00, 79.00, 'USD', 40, 'in_stock', (SELECT id FROM categories WHERE slug='women'), 1, 'percentage', 8.00, 'published', 0, 'public'),
(1, NULL, 'Handbag', 'handbag', 'Designer leather handbag.', 'Elegant handbag.', 149.00, 199.00, 'USD', 25, 'in_stock', (SELECT id FROM categories WHERE slug='women'), 1, 'percentage', 8.00, 'published', 1, 'public'),
(1, NULL, 'Modern Sofa', 'modern-sofa', '3-seater fabric sofa.', 'Living room sofa.', 699.00, 899.00, 'USD', 8, 'in_stock', (SELECT id FROM categories WHERE slug='furniture'), 1, 'percentage', 5.00, 'published', 1, 'public'),
(1, NULL, 'Dining Table', 'dining-table', 'Oak dining table for 6.', 'Wooden dining table.', 499.00, 649.00, 'USD', 6, 'in_stock', (SELECT id FROM categories WHERE slug='furniture'), 1, 'percentage', 5.00, 'published', 0, 'public'),
(1, NULL, 'Air Fryer', 'air-fryer', 'Digital air fryer for healthy cooking.', 'Kitchen appliance.', 89.00, 129.00, 'USD', 45, 'in_stock', (SELECT id FROM categories WHERE slug='kitchen'), 1, 'percentage', 7.00, 'published', 0, 'public'),
(1, NULL, 'Coffee Maker', 'coffee-maker', 'Programmable drip coffee maker.', 'Morning essential.', 79.00, 99.00, 'USD', 38, 'in_stock', (SELECT id FROM categories WHERE slug='kitchen'), 1, 'percentage', 7.00, 'published', 0, 'public'),
(1, NULL, 'Skincare Set', 'skincare-set', 'Daily facial skincare essentials.', 'Beauty bundle.', 69.00, 89.00, 'USD', 60, 'in_stock', (SELECT id FROM categories WHERE slug='beauty-health'), 1, 'percentage', 8.00, 'published', 0, 'public'),
(1, NULL, 'Protein Powder', 'protein-powder', 'Whey protein for fitness.', '2lb protein.', 49.00, 59.00, 'USD', 80, 'in_stock', (SELECT id FROM categories WHERE slug='beauty-health'), 1, 'percentage', 7.00, 'published', 0, 'public'),
(1, NULL, 'Yoga Mat', 'yoga-mat', 'Non-slip exercise yoga mat.', 'Workout mat.', 29.00, 39.00, 'USD', 100, 'in_stock', (SELECT id FROM categories WHERE slug='sports-outdoors'), 1, 'percentage', 8.00, 'published', 0, 'public'),
(1, NULL, 'Camping Tent', 'camping-tent', '4-person weatherproof tent.', 'Family tent.', 159.00, 199.00, 'USD', 15, 'in_stock', (SELECT id FROM categories WHERE slug='sports-outdoors'), 1, 'percentage', 7.00, 'published', 1, 'public'),
(1, NULL, 'Board Game', 'board-game', 'Strategy board game for 2-6 players.', 'Fun for game night.', 39.00, 49.00, 'USD', 55, 'in_stock', (SELECT id FROM categories WHERE slug='toys-games'), 1, 'percentage', 8.00, 'published', 0, 'public'),
(1, NULL, 'Car Dash Cam', 'car-dash-cam', '1080p front and rear dash cam.', 'Safety accessory.', 79.00, 109.00, 'USD', 28, 'in_stock', (SELECT id FROM categories WHERE slug='automotive'), 1, 'percentage', 7.00, 'published', 0, 'public'),
(1, NULL, 'Tire Inflator', 'tire-inflator', 'Portable electric tire pump.', 'Roadside helper.', 34.00, 49.00, 'USD', 42, 'in_stock', (SELECT id FROM categories WHERE slug='automotive'), 1, 'percentage', 8.00, 'published', 0, 'public');
